_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 54
                - 55
                - 63
            "2":
                - 1
                - 5
                - 12
                - 41
                - 49
                - 53
                - 54
                - 55
                - 63
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.16
            "5": 0.18.3
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
batch_size:
    value: 32
dec_blk_type:
    value: adaLN
dec_depth:
    value: 3
dec_norm_init:
    value: true
dec_num_heads:
    value: 4
device:
    value: cuda:0
enc_affine:
    value: true
enc_depth:
    value: 3
enc_dim:
    value: 22
enc_norm_type:
    value: ln
enc_num_heads:
    value: 4
epoch:
    value: 200
expand_dim:
    value: 256
hidden_dim:
    value: 64
is_data_scaled:
    value: true
is_initialize:
    value: true
is_lr_scheduler:
    value: true
iter:
    value: 10000
lr:
    value: 6.7e-05
seed:
    value: 1202
weight_decay:
    value: 5e-06
